In [2]:
import numpy as np
call=np.array([5,6,7,8])
print(call)

[5 6 7 8]


In [20]:
dimensional=np.array((['jan','feb','mar'],
             [300,400,500],
             [600,700,800]))
print(dimensional.shape)
print(dimensional)

(3, 3)
[['jan' 'feb' 'mar']
 ['300' '400' '500']
 ['600' '700' '800']]


In [21]:
mc=np.array((['jan','feb','mar'],
             [300,400,500],
             [600,700,800]))
mc[2][2]

np.str_('800')

In [ ]:
mc=np.array((['jan','feb','mar'],
             [300,400,500],
             [600,700,800]))
mc[0:,1]

np.str_('feb')

In [31]:
sr = np.array([3.6,4,2,6,1,3])
sr[sr>3]

array([3.6, 4. , 6. ])

In [44]:
sr = np.array([3,6,4,2,6,1,3])
sr[(sr>2) & (sr<4)]

array([3, 3])

In [57]:
dimensional=np.array(([300,400,500],
             [600,700,800]))
print(np.sum(dimensional))

3300


In [64]:
dimensional=np.array((['jan','feb','mar'],
             [300,400,500],
             [600,700,800]))
print(np.sum (dimensional[1:].astype('int')))

3300


In [68]:
North = np.array([5,60,90])
South = np.array([3,20,5])
print(np.concatenate((North,South)))

[ 5 60 90  3 20  5]


In [70]:
np.add(dimensional[1:,].astype('int'),dimensional[2:,].astype('int'))

array([[ 900, 1100, 1300],
       [1200, 1400, 1600]])